import Foundation

/// The exact bytes both sides sign during the identity handshake.
///
/// This must match `challenge_material` in `src/nova_voice/companion/auth.py`
/// byte for byte — a mismatch is not a decoding error, it is a signature that
/// silently never verifies, which is a miserable thing to debug from a phone.
/// `Tests/…/ChallengeTests` pins it against a vector generated by the Python
/// side, so a change to either implementation breaks a test rather than the
/// handshake.
///
/// All four inputs are covered by one signature so none of them can be
/// substituted afterwards: a valid signature over a different announced id or
/// a different role list is not a valid signature for this connection.
public enum CompanionChallenge {
    public static let prefix = "nova-companion-auth-v1"

    public static func material(
        nonce: String,
        protocolVersion: Int = CompanionProtocol.version,
        announcedId: String,
        roles: [String]
    ) -> Data {
        let normalisedRoles = roles
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() }
            .sorted()
            .joined(separator: ",")
        let joined = [
            prefix,
            nonce,
            String(protocolVersion),
            announcedId.trimmingCharacters(in: .whitespacesAndNewlines).lowercased(),
            normalisedRoles,
        ].joined(separator: "|")
        return Data(joined.utf8)
    }

    public static func material(
        nonce: String,
        protocolVersion: Int = CompanionProtocol.version,
        announcedId: String,
        roles: [CompanionRole]
    ) -> Data {
        material(
            nonce: nonce,
            protocolVersion: protocolVersion,
            announcedId: announcedId,
            roles: roles.map(\.rawValue)
        )
    }
}
