#!/usr/bin/env bash
set -euo pipefail

# Configure the Nocturnium PipeWire echo-cancel module against the machine's
# actual default source/sink. PipeWire node names are host-specific (the old
# PCI-id example silently produced a graph with no physical capture), so this
# script resolves them at install time and writes a user-owned override.

CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/pipewire/pipewire.conf.d"
CONF_PATH="$CONF_DIR/60-nova-voice-aec.conf"
CAPTURE_TARGET=""
PLAYBACK_TARGET=""
RESTART=0

usage() {
  echo "Usage: $0 [--capture NODE_NAME] [--playback NODE_NAME] [--restart]" >&2
  echo "       NODE_NAME defaults to the current PipeWire default source/sink." >&2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --capture)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      CAPTURE_TARGET="$2"
      shift 2
      ;;
    --playback)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      PLAYBACK_TARGET="$2"
      shift 2
      ;;
    --restart)
      RESTART=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

command -v wpctl >/dev/null 2>&1 || {
  echo "wpctl is required (PipeWire/WirePlumber is not available)" >&2
  exit 2
}

node_name() {
  local object="$1"
  # wpctl inspect emits node.name = "...". Keep parsing deliberately narrow
  # because the value is inserted into a PipeWire config file below.
  wpctl inspect "$object" 2>/dev/null \
    | awk -F'"' '/node\.name[[:space:]]*=/ { print $2; exit }'
}

existing_target() {
  local block="$1"
  [[ -f "$CONF_PATH" ]] || return 0
  awk -v block="$block" '
    $0 ~ block "\\.props" { inside = 1; next }
    inside && /}/ { exit }
    inside && /target\.object/ {
      if (match($0, /"[^"]+"/)) print substr($0, RSTART + 1, RLENGTH - 2)
      exit
    }
  ' "$CONF_PATH"
}

aec_node_id() {
  local name="$1"
  wpctl status -n 2>/dev/null | awk -v name="$name" '
    {
      for (field = 1; field <= NF; field++) {
        if ($field == name) {
          id = $(field - 1)
          gsub(/[^0-9]/, "", id)
          print id
          exit
        }
      }
    }
  '
}

[[ -n "$CAPTURE_TARGET" ]] || CAPTURE_TARGET="$(node_name @DEFAULT_AUDIO_SOURCE@)"
[[ -n "$PLAYBACK_TARGET" ]] || PLAYBACK_TARGET="$(node_name @DEFAULT_AUDIO_SINK@)"

# Once configured, the virtual AEC nodes deliberately become the user defaults
# so PortAudio's generic PipeWire ALSA device routes through them. A later rerun
# must retain the physical targets rather than pointing the module back at
# itself and creating a silent loop.
if [[ "$CAPTURE_TARGET" == "nova_voice_aec" ]]; then
  CAPTURE_TARGET="$(existing_target capture)"
fi
if [[ "$PLAYBACK_TARGET" == "nova_voice_aec_sink" ]]; then
  PLAYBACK_TARGET="$(existing_target playback)"
fi

valid_node() {
  [[ "$1" =~ ^[A-Za-z0-9_.:-]+$ ]]
}
if ! valid_node "$CAPTURE_TARGET" || ! valid_node "$PLAYBACK_TARGET"; then
  echo "Could not resolve safe PipeWire source/sink node names" >&2
  echo "capture='$CAPTURE_TARGET' playback='$PLAYBACK_TARGET'" >&2
  echo "Pass --capture and --playback with the names shown by 'wpctl status -n'." >&2
  exit 1
fi

install -d -m 0700 "$CONF_DIR"
temporary="$(mktemp "$CONF_DIR/.nova-voice-aec.XXXXXX")"
trap 'rm -f "$temporary"' EXIT
cat >"$temporary" <<EOF
# Generated by nova-voice/ops/configure-pipewire-aec.sh.
# Source/sink names are discovered on this host; do not replace with a PCI id.
context.modules = [
    { name = libpipewire-module-echo-cancel
        args = {
            library.name = aec/libspa-aec-webrtc
            node.latency = 480/48000
            capture.props = {
                node.name = "nova_voice_aec_capture"
                target.object = "$CAPTURE_TARGET"
            }
            source.props = {
                node.name = "nova_voice_aec"
                node.description = "Nova Voice Echo-Cancelled Microphone"
            }
            sink.props = {
                node.name = "nova_voice_aec_sink"
                node.description = "Nova Voice Echo Reference"
            }
            playback.props = {
                node.name = "nova_voice_aec_playback"
                target.object = "$PLAYBACK_TARGET"
            }
        }
    }
]
EOF
chmod 0600 "$temporary"
mv -f "$temporary" "$CONF_PATH"
trap - EXIT

echo "Wrote $CONF_PATH"
echo "  capture target: $CAPTURE_TARGET"
echo "  playback target: $PLAYBACK_TARGET"

if (( RESTART )); then
  systemctl --user restart pipewire.service wireplumber.service
  # Give the module a moment to register, then fail loudly if no virtual
  # source appeared. This prevents silently claiming AEC capability.
  for _ in {1..10}; do
    if wpctl status -n 2>/dev/null | grep -Fq nova_voice_aec; then
      capture_id="$(aec_node_id nova_voice_aec)"
      playback_id="$(aec_node_id nova_voice_aec_sink)"
      if [[ -z "$capture_id" || -z "$playback_id" ]]; then
        echo "AEC nodes appeared but their PipeWire ids could not be resolved" >&2
        exit 1
      fi
      wpctl set-default "$capture_id"
      wpctl set-default "$playback_id"
      defaults_ready=0
      for _ in {1..10}; do
        if [[ "$(node_name @DEFAULT_AUDIO_SOURCE@)" == "nova_voice_aec" \
          && "$(node_name @DEFAULT_AUDIO_SINK@)" == "nova_voice_aec_sink" ]]; then
          defaults_ready=1
          break
        fi
        sleep 0.2
      done
      if (( ! defaults_ready )); then
        echo "AEC nodes exist but could not be selected as PipeWire defaults" >&2
        exit 1
      fi
      echo "Nova Voice AEC nodes are present and selected as defaults"
      exit 0
    fi
    sleep 1
  done
  echo "PipeWire restarted but nova_voice_aec nodes were not observed" >&2
  exit 1
fi

echo "Restart PipeWire/WirePlumber after reviewing the generated graph (use --restart)."
